.github/workflows/push.yml, .github/workflows/tag.yml, infrastructure/docker/cover-service-importers/Dockerfile, infrastructure/docker/cover-service-importers/docker-entrypoint.sh, infrastructure/docker/cover-service-jobs/Dockerfile, infrastructure/docker/run.sh, infrastructure/k8s/app-import-pod.yaml, infrastructure/k8s/cron-job-bogportal.yaml, infrastructure/k8s/cron-job-config.yaml, infrastructure/k8s/cron-job-publizon.yaml, infrastructure/k8s/stg/cron-job-config.yaml
To automatically run imports form the two major vendors.
=> DDBTEAM-404: Added k8s cronjobs

src/Command/Search/SearchReindexCommand.php, src/Queue/SearchProcessor.php, src/Service/OpenPlatform/SearchService.php, src/Service/VendorService/ProgressBarTrait.php, src/Utils/Types/VendorState.php
https://jira.itkdev.dk/browse/DDBTEAM-421
=> DDBTEAM-421: Added support for reindex search with clean-up

src/Service/VendorService/Chandos/ChandosVendorService.php
Requires: https://github.com/danskernesdigitalebibliotek/ddb-cover-service-importers/pull/18
=> Chandos vendor service

src/Command/QueueInsertCommand.php, src/Queue/CoverUploadProcessor.php
https://jira.itkdev.dk/browse/DDBTEAM-442
=> DDBTEAM-442: Small debug fixes to upload queue processor

src/Service/VendorService/UploadService/UploadServiceVendorService.php, tests/UploadServiceVendorServiceTest.php
https://jira.itkdev.dk/browse/DDBTEAM-462
=> Match type should not always be ISBN

src/Command/QueueInsertCommand.php, src/Event/VendorEvent.php, src/Queue/CoverUploadProcessor.php, src/Queue/DeleteProcessor.php, src/Utils/Types/VendorState.php
https://jira.itkdev.dk/browse/DDBTEAM-461
The whole process have been test in hand with the queue command.
=> Better support for upload delete events

src/Service/VendorService/UploadService/UploadServiceVendorService.php
https://jira.itkdev.dk/browse/DDBTEAM-478
=> DDBTEAM-478: Rename uploaded file to match identifier

src/Service/VendorService/EBP/EBPVendorService.php
https://jira.itkdev.dk/browse/DDBTEAM-452
=> DDBTEAM-452: Added EBP's music vendor service

.env, composer.json, config/packages/cache.yaml, config/packages/framework.yaml, config/packages/github_actions/framework.yaml, config/packages/prod/cache.yaml, infrastructure/cover-service-cron-jobs/templates/configmap.yaml, infrastructure/cover-service-cron-jobs/values.yaml, infrastructure/cover-service-importers/templates/configmap.yaml, infrastructure/cover-service-importers/values.yaml, infrastructure/docker/cover-service-importers/Dockerfile, infrastructure/docker/cover-service-importers/docker-entrypoint.sh, infrastructure/docker/cover-service-importers/etc/confd/templates/env.local.tmpl, infrastructure/docker/cover-service-jobs/docker-entrypoint.sh
* Fixed hack build hack
* Add redis cache prefix
=> DDBTEAM-522: Updated build process to match other services

composer.json, composer.lock, src/Service/OpenPlatform/SearchService.php, symfony.lock
https://jira.itkdev.dk/browse/DDBTEAM-511
=> DDBTEAM-511: Added support wider match with ISBN

src/Service/VendorService/AbstractTsvVendorService.php, src/Service/VendorService/VendorImageValidatorService.php
https://jira.itkdev.dk/browse/DDBTEAM-532
=> DDBTEAM-532: Added url validation to TSV importer

src/Command/Search/SearchReindexCommand.php, src/Command/Source/SourceUpdateImageMetaCommand.php, src/Queue/SearchProcessor.php, src/Service/OpenPlatform/SearchService.php, src/Utils/CoverVendor/VendorImageItem.php, src/Utils/Message/ProcessMessage.php
`bin/console app:search:reindex --vendor-id=1 --identifier=9788771807592 --without-search-cache`
=> DDBTEAM-542: Updated search re-index commands

src/Command/QueueInsertCommand.php, src/Exception/MaterialConversionException.php, src/Queue/CoverStoreAutoProcessor.php, src/Queue/CoverStoreProcessor.php, src/Queue/CoverUserUploadProcessor.php, src/Queue/DeleteProcessor.php, src/Queue/SearchNoHitsProcessor.php, src/Queue/SearchProcessor.php, src/Queue/VendorImageProcessor.php, src/Service/OpenPlatform/SearchService.php, src/Service/VendorService/UserUpload/UserUploadVendorService.php, src/Utils/OpenPlatform/Material.php
* New UserUpload vendor to split it from bulk upload
* Handle no-hit on katelog posts
Requires: https://github.com/danskernesdigitalebibliotek/ddb-cover-service-upload/pull/27
=> User uploaded covers

.github/workflows/pr.yaml, src/Command/CoverStore/CoverStoreValidateImageCommand.php
https://jira.itkdev.dk/browse/AAKBET-707
=> DDBTEAM-707: Added new command to clean up failed upload

src/Queue/SearchNoHitsProcessor.php
Simply move if statement from first if into outer if for both statements...
=> DDBTEAM-648: Ensured source exists for all no-hit processing

composer.lock, src/Service/VendorService/BogPortalen/BogPortalenVendorService.php, symfony.lock
Change to `putStream()` and `readStream()` 
Tried to see if we easily could get better memory usage in the progress bar but it only has "The current memory usage", not peak usage: https://symfony.com/doc/current/components/console/helpers/progressbar.html#custom-formats
=> DDBTEAM-666: Update bogportalen to use streams

docker-compose.yml, src/Service/OpenPlatform/SearchService.php
https://jira.itkdev.dk/browse/DDBTEAM-714
=> Hotfix: Search limit and retry limit

composer.json, config/packages/prod/doctrine.yaml, src/Entity/Image.php, src/Entity/Search.php, src/Entity/Source.php, src/Entity/Vendor.php, src/EventSubscriber/IndexEventSubscriber.php, src/MessageHandler/SearchNoHitsMessageHandler.php, src/Migrations/Version20211102093204.php, src/Service/OpenPlatform/SearchService.php, src/Service/PopulateService.php, src/Utils/OpenPlatform/Material.php
https://jira.itkdev.dk/browse/DDBTEAM-861
=> Changes to mappings

src/Service/OpenPlatform/SearchService.php
After a lot of ping/pong with aakb search team we found that katelog posts (påhængsposter/lokaleposter) if they exists overrides the basic post in the open platform search matching.
So this will make an extra search if no basic post is found to ensure that we always tries to find a basic post id.
```
-----------------------------------------
Title: Ternet Ninja. Bind 2
Creator: Anders Matthesen
Date: 2021
Publisher: Høst
Collection: true
-----------------------------------------
----           Identifiers           ----
-----------------------------------------
pid: 800010-katalog:99123820325705763__1
pid: 775100-katalog:39286149
pid: 870970-basis:39286149
isbn: 9788702307047
isbn: 8702307049
faust: 39286149
------------------------------------------
```
=> DDBTEAM-931: Added extra search to ensure basic post is found

composer.json, src/Command/Source/SourceDownloadCoversCommand.php, src/MessageHandler/CoverUserUploadMessageHandler.php, src/Service/PopulateService.php, src/Service/VendorService/VendorImageValidatorService.php
Fixed 12 user upload images: `bin/console app:source:download --vendor-id=15`
=> Updated command to upload cover images

src/MessageHandler/CoverUserUploadMessageHandler.php
https://jira.itkdev.dk/browse/DDBTEAM-979
Trying to fix ```A new entity was found through the relationship 'App\Entity\Source#vendor'
that was not configured to cascade persist operations for entity.```
No screenshot.
No comments.
=> DDBTEAM-979: Trying to fix renadom database error on user upload

src/Service/DataWell/SearchService.php, src/Service/VendorService/DataWell/DataWellSearchService.php, src/Service/VendorService/PressReader/PressReaderVendorService.php, src/Service/VendorService/VendorImageValidatorService.php, tests/Service/VendorService/VendorImageValidatorServiceTest.php
https://jira.itkdev.dk/browse/DDBTEAM-990
https://platform.dandigbib.org/issues/5358
Adding new vendor to fetch covers from press readers CDN.
No comments
=> DDBTEAM-990: Added PressReader vendor service

src/Command/Source/SourceDownloadCoversCommand.php, src/Command/Source/SourceUpdateImageMetaCommand.php
https://jira.itkdev.dk/browse/DDBTEAM-990
Added more filter options to the to source table related commands.
No screenshot.
No comments.
=> DDBTEAM-990: Added more options to source commands

baseline.xml, composer.json, composer.lock, src/MessageHandler/SearchNoHitsMessageHandler.php, src/Repository/SourceRepository.php, src/Service/CoverStore/CloudinaryCoverStoreService.php, src/Service/CoverStore/CloudinaryTransformationService.php, src/Service/CoverStore/CoverStoreTransformationInterface.php, symfony.lock, tests/Service/CoverStore/CoverStoreTransformationServiceTest.php
No ticket.
Upgrade the to the newer API v2 for the cover store.
Following this page: https://cloudinary.com/documentation/php2_migration
No screenshot.
No comments.
=> Upgraded to Cloudinary api version 2

.markdownlint.json, CHANGELOG.md, src/Service/VendorService/DataWell/DataConverter/AmazonPublicUrlConverter.php, src/Service/VendorService/DataWell/DataConverter/IversePublicUrlConverter.php, src/Service/VendorService/DataWell/DataWellVendorService.php, tests/Service/VendorService/DataWell/DataConverter/AmazonPublicUrlConverterTest.php
https://jira.itkdev.dk/browse/DDBTEAM-1012
Vendor has change to use AWS CDN, so url pattern has changed.
If your change affects the user interface you should include a screenshot of the result with the pull request.
If you have any further comments or questions for the reviewer please add them here.
=> DDBTEAM-1012: Updated url pattern to match new CDN

.github/workflows/upgrade.yaml
https://jira.itkdev.dk/browse/DDBTEAM-990
Added workflows to test for php upgradability. 
No screenshot.
No comments.
=> DDBTEAM-990: Test php 8.x

.github/workflows/pr.yaml, .github/workflows/upgrade.yaml, infrastructure/cover-service-cron-jobs/templates/configmap.yaml, infrastructure/cover-service-cron-jobs/values.yaml, infrastructure/cover-service-importers/templates/configmap.yaml, infrastructure/cover-service-importers/values.yaml, infrastructure/docker/cover-service-importers/Dockerfile, infrastructure/docker/cover-service-importers/etc/confd/templates/env.local.tmpl, migrations/Version20220708121805.php
https://jira.itkdev.dk/browse/DDBTEAM-948
Update docker builds and helm charts.
If your change affects the user interface you should include a screenshot of the result with the pull request.
If you have any further comments or questions for the reviewer please add them here.
=> DDBTEAM-1011: Updated helm chats and docker

CHANGELOG.md, src/Command/QueueInsertCommand.php, src/Service/VendorService/VendorImageValidatorService.php
https://jira.itkdev.dk/browse/DDBTEAM-1029
Fixed wrong http client options in image validation.
No screenshot.
No comments.
=> DDBTEAM-1029: Fixed options to http client in image validator

CHANGELOG.md, config/services.yaml, migrations/Version20221109155146.php, src/Command/OpenPlatform/OpenPlatformAuthCommand.php, src/Command/OpenPlatform/OpenPlatformSearchCommand.php, src/Entity/Search.php, src/Message/AbstractBaseMessage.php, src/Message/CoverUserUploadMessage.php, src/MessageHandler/CoverStoreMessageHandler.php, src/MessageHandler/CoverUserUploadMessageHandler.php, src/MessageHandler/SearchMessageHandler.php, src/MessageHandler/SearchNoHitsMessageHandler.php, src/MessageHandler/VendorImageMessageHandler.php, src/Repository/SearchRepository.php, src/Service/OpenPlatform/AuthenticationService.php, src/Service/OpenPlatform/SearchService.php, src/Utils/OpenPlatform/Material.php, tests/Service/OpenPlatform/AuthenticationServiceTest.php, tests/Service/OpenPlatform/SearchServiceTest.php
https://jira.itkdev.dk/browse/COVER-15
N/A
N/A
Requires: https://github.com/danskernesdigitalebibliotek/ddb-cover-service/pull/145 and https://github.com/danskernesdigitalebibliotek/ddb-cover-service-upload/pull/55
=> Ture's ide 1

composer.lock, docker-compose.yml
https://jira.itkdev.dk/browse/COVER-19
Update ES til 8.5.2
N/A
N/A
=> COVER-19: Updated ES til 8.5.2

CHANGELOG.md, config/services.yaml, src/MessageHandler/DeleteMessageHandler.php, src/MessageHandler/IndexMessageHandler.php, src/Service/Indexing/IndexingElasticService.php, src/Service/Indexing/IndexingServiceInterface.php, src/Service/PopulateService.php
https://jira.itkdev.dk/browse/COVER-19
* Fixed http response status checks for elastic index service
* Renamed methods to match elastic naming, E.g. `remove()` -> `delete()` etc
If your change affects the user interface you should include a screenshot of the result with the pull request.
If you have any further comments or questions for the reviewer please add them here.
=> COVER-19: Fixed http response status checks for elastic index service

src/Service/VendorService/OverDrive/OverDriveBooksVendorService.php
https://jira.itkdev.dk/browse/COVER-34
- Added missing delimiter to regex pattern
N/A
If you have any further comments or questions for the reviewer please add them here.
=> COVER-34: Added delimiter to regex pattern
